import { YTNode } from '../../helpers.js';
import { type RawNode } from '../../index.js';

export type UploadChecksSummaryStatus =
  'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_COMPLETED' | 'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_EXTENDED_CHECK_STARTED' |
  'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_INLINE_EDIT_IN_PROGRESS' | 'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_NOT_STARTED' |
  'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_OVERDUE' | 'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_SELF_CERTIFICATION_MISSING' |
  'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_SHORTS_NOT_ELIGIBLE' | 'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_STARTED' |
  'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_UNABLE_TO_RUN' | 'UPLOAD_CHECKS_DATA_SUMMARY_STATUS_UNKNOWN';

export type UploadChecksCopyrightStatus =
  'UPLOAD_CHECKS_DATA_COPYRIGHT_STATUS_COMPLETED' | 'UPLOAD_CHECKS_DATA_COPYRIGHT_STATUS_INLINE_EDIT_IN_PROGRESS' |
  'UPLOAD_CHECKS_DATA_COPYRIGHT_STATUS_NOT_STARTED' | 'UPLOAD_CHECKS_DATA_COPYRIGHT_STATUS_OVERDUE' |
  'UPLOAD_CHECKS_DATA_COPYRIGHT_STATUS_SHORTS_NOT_ELIGIBLE' | 'UPLOAD_CHECKS_DATA_COPYRIGHT_STATUS_STARTED' |
  'UPLOAD_CHECKS_DATA_COPYRIGHT_STATUS_UNABLE_TO_RUN' | 'UPLOAD_CHECKS_DATA_COPYRIGHT_STATUS_UNKNOWN';

export type UploadChecksAdSuitabilityStatus =
  'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_CHANNEL_NOT_MONETIZED' | 'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_COMPLETED' |
  'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_EXTENDED_CHECK_STARTED' | 'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_NOT_STARTED' |
  'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_OVERDUE' | 'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_SELF_CERTIFICATION_MISSING' |
  'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_SHORTS_NOT_ELIGIBLE' | 'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_STARTED' |
  'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_UNABLE_TO_RUN' | 'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_UNKNOWN' |
  'UPLOAD_CHECKS_DATA_AD_SUITABILITY_STATUS_VIDEO_NOT_MONETIZED';

export type UploadChecksCommunityGuidelinesStatus =
  'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_COMPLETED' | 'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_NOT_AVAILABLE_ON_PUBLISHED_VIDEO' |
  'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_NOT_ELIGIBLE' | 'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_NOT_STARTED' |
  'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_OVERDUE' | 'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_SHORTS_NOT_ELIGIBLE' |
  'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_STARTED' | 'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_UNABLE_TO_RUN' |
  'UPLOAD_CHECKS_DATA_COMMUNITY_GUIDELINES_STATUS_UNKNOWN';

export default class VideoUploadChecks extends YTNode {
  static type = 'VideoUploadChecks';

  checks_summary?: UploadChecksSummaryStatus;
  copyright_check?: UploadChecksCopyrightStatus;
  ad_suitability_check?: UploadChecksAdSuitabilityStatus;
  community_guidelines_check?: UploadChecksCommunityGuidelinesStatus;

  constructor(data: RawNode) {
    super();

    if (Reflect.has(data, 'checksSummary') && Reflect.has(data.checksSummary, 'status')) {
      this.checks_summary = data.checksSummary.status;
    }

    if (Reflect.has(data, 'copyrightCheck') && Reflect.has(data.copyrightCheck, 'checkStatus')) {
      this.copyright_check = data.copyrightCheck.checkStatus;
    }

    if (Reflect.has(data, 'adSuitabilityCheck') && Reflect.has(data.adSuitabilityCheck, 'checkStatus')) {
      this.ad_suitability_check = data.adSuitabilityCheck.checkStatus;
    }

    if (Reflect.has(data, 'communityGuidelinesCheck') && Reflect.has(data.communityGuidelinesCheck, 'checkStatus')) {
      this.community_guidelines_check = data.communityGuidelinesCheck.checkStatus;
    }
  }
}
