version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
          