name: Issue Report
title: "<version> <title>"
description: Use this template to report a problem
labels: [bug]
body:
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps for reproducing the issue.
      placeholder: |
        Example:
          1. Step 1
          2. Step 2
          3. You get it..
    validations:
      required: true
  
  - type: textarea
    id: failure-logs
    attributes:
      label: Failure Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: What is the current behavior?
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the library are you running?
      options:
        - Default
        - Edge
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
   
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am running the latest version.
          required: false
        - label: I checked the documentation and found no answer.
          required: true      
        - label: I have searched the existing issues and made sure this is not a duplicate.
          required: true        
        - label: I have provided sufficient information.
          required: true
