name: Question
description: Use this template to ask a question about the project
labels: [question]
body:

  - type: textarea
    id: question
    attributes:
      label: Question    
      placeholder: What do you want to know?
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am running the latest version.
          required: true
        - label: I checked the documentation and found no answer.
          required: true      
        - label: I have searched the existing issues and made sure this is not a duplicate.
          required: true        
        - label: I have provided sufficient information.
          required: true
